version: '3'
services:
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    ports:
      - "8080:80"
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8080
      - ADMIN_DIR=admin-shop
      - PS_FOLDER_ADMIN=admin-shop
      - PS_FOLDER_INSTALL=install
    volumes:
      - ./themes:/var/www/html/themes
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: prestashop_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
